// This file is generated by scripts/generate-runtime-migrations.mjs.
// Regenerate it whenever a migration is added or changed.
import type { RuntimeDatabaseMigration } from "./setup-database-migrations.types";

export const runtimeDatabaseMigrations: RuntimeDatabaseMigration[] = [
  {
    "name": "0000_init.sql",
    "statements": [
      "CREATE TABLE `users` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`email` text NOT NULL,\n\t`name` text NOT NULL,\n\t`password_hash` text NOT NULL,\n\t`store_name` text NOT NULL,\n\t`store_slug` text NOT NULL,\n\t`created_at` text NOT NULL\n);",
      "CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);",
      "CREATE UNIQUE INDEX `users_store_slug_unique` ON `users` (`store_slug`);",
      "CREATE TABLE `products` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`slug` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`price` integer NOT NULL,\n\t`currency` text DEFAULT 'USD' NOT NULL,\n\t`status` text DEFAULT 'draft' NOT NULL,\n\t`image_url` text,\n\t`delivery_content` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `orders` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`product_id` text NOT NULL,\n\t`product_name` text NOT NULL,\n\t`amount` integer NOT NULL,\n\t`currency` text NOT NULL,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`customer_email` text NOT NULL,\n\t`customer_name` text,\n\t`paypal_order_id` text,\n\t`paypal_capture_id` text,\n\t`gateway` text DEFAULT 'paypal' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`paid_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `paypal_connections` (\n\t`user_id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`client_secret_encrypted` text NOT NULL,\n\t`mode` text DEFAULT 'sandbox' NOT NULL,\n\t`merchant_email` text,\n\t`connected_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);"
    ]
  },
  {
    "name": "0001_environment_modes.sql",
    "statements": [
      "ALTER TABLE `users` ADD `environment` text DEFAULT 'sandbox' NOT NULL;",
      "PRAGMA foreign_keys=OFF;",
      "CREATE TABLE `__new_paypal_connections` (\n\t`user_id` text NOT NULL,\n\t`client_id` text NOT NULL,\n\t`client_secret_encrypted` text NOT NULL,\n\t`mode` text DEFAULT 'sandbox' NOT NULL,\n\t`merchant_email` text,\n\t`connected_at` text NOT NULL,\n\tPRIMARY KEY(`user_id`, `mode`),\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "INSERT INTO `__new_paypal_connections`(\n\t\"user_id\",\n\t\"client_id\",\n\t\"client_secret_encrypted\",\n\t\"mode\",\n\t\"merchant_email\",\n\t\"connected_at\"\n)\nSELECT\n\t\"user_id\",\n\t\"client_id\",\n\t\"client_secret_encrypted\",\n\t\"mode\",\n\t\"merchant_email\",\n\t\"connected_at\"\nFROM `paypal_connections`;",
      "DROP TABLE `paypal_connections`;",
      "ALTER TABLE `__new_paypal_connections` RENAME TO `paypal_connections`;",
      "PRAGMA foreign_keys=ON;"
    ]
  },
  {
    "name": "0002_dashboard_features.sql",
    "statements": [
      "CREATE TABLE `feature_records` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`feature` text NOT NULL,\n\t`title` text NOT NULL,\n\t`subtitle` text,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`data` text DEFAULT '{}' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `feature_records_user_feature_idx` ON `feature_records` (`user_id`,`feature`);",
      "CREATE TABLE `api_keys` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`key_prefix` text NOT NULL,\n\t`key_hash` text NOT NULL,\n\t`last_used_at` text,\n\t`expires_at` text,\n\t`revoked_at` text,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `api_keys_key_hash_unique` ON `api_keys` (`key_hash`);",
      "CREATE INDEX `api_keys_user_idx` ON `api_keys` (`user_id`);",
      "ALTER TABLE `orders` ADD `discount_code` text;",
      "ALTER TABLE `orders` ADD `discount_amount` integer DEFAULT 0 NOT NULL;",
      "ALTER TABLE `orders` ADD `affiliate_id` text;",
      "ALTER TABLE `orders` ADD `environment` text DEFAULT 'sandbox' NOT NULL;"
    ]
  },
  {
    "name": "0003_paypal_webhooks.sql",
    "statements": [
      "ALTER TABLE `paypal_connections` ADD `webhook_id` text;",
      "ALTER TABLE `paypal_connections` ADD `webhook_url` text;",
      "ALTER TABLE `paypal_connections` ADD `webhook_status` text DEFAULT 'not_configured' NOT NULL;",
      "ALTER TABLE `paypal_connections` ADD `webhook_error` text;"
    ]
  },
  {
    "name": "0004_notifications.sql",
    "statements": [
      "CREATE TABLE `notifications` (\n  `id` text PRIMARY KEY NOT NULL,\n  `user_id` text NOT NULL,\n  `type` text NOT NULL,\n  `title` text NOT NULL,\n  `message` text,\n  `href` text,\n  `source_key` text NOT NULL,\n  `read_at` text,\n  `created_at` text NOT NULL,\n  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `notifications_user_created_idx` ON `notifications` (`user_id`,`created_at`);",
      "CREATE INDEX `notifications_user_read_idx` ON `notifications` (`user_id`,`read_at`);",
      "CREATE UNIQUE INDEX `notifications_user_source_idx` ON `notifications` (`user_id`,`source_key`);"
    ]
  },
  {
    "name": "0005_product_license_setting.sql",
    "statements": [
      "ALTER TABLE `products` ADD `generate_license` integer DEFAULT false NOT NULL;"
    ]
  },
  {
    "name": "0006_github_repository_delivery.sql",
    "statements": [
      "CREATE TABLE `github_connections` (\n  `user_id` text PRIMARY KEY NOT NULL,\n  `github_user_id` text NOT NULL,\n  `login` text NOT NULL,\n  `access_token_encrypted` text NOT NULL,\n  `scopes` text DEFAULT '' NOT NULL,\n  `connected_at` text NOT NULL,\n  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "ALTER TABLE `products` ADD `github_repo_owner` text;",
      "ALTER TABLE `products` ADD `github_repo_name` text;",
      "ALTER TABLE `orders` ADD `github_username` text;",
      "ALTER TABLE `orders` ADD `github_access_status` text DEFAULT 'not_required' NOT NULL;",
      "ALTER TABLE `orders` ADD `github_access_managed` integer DEFAULT false NOT NULL;",
      "ALTER TABLE `orders` ADD `github_invitation_id` text;",
      "ALTER TABLE `orders` ADD `github_access_error` text;",
      "ALTER TABLE `orders` ADD `github_access_granted_at` text;",
      "ALTER TABLE `orders` ADD `github_access_revoked_at` text;"
    ]
  },
  {
    "name": "0007_github_oauth_hostname.sql",
    "statements": [
      "ALTER TABLE `users` ADD `github_oauth_hostname` text;"
    ]
  },
  {
    "name": "0008_multi_store.sql",
    "statements": [
      "CREATE TABLE `stores` (\n  `id` text PRIMARY KEY NOT NULL,\n  `user_id` text NOT NULL,\n  `name` text NOT NULL,\n  `slug` text NOT NULL,\n  `cover_image_url` text,\n  `created_at` text NOT NULL,\n  `updated_at` text NOT NULL,\n  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `stores_slug_idx` ON `stores` (`slug`);",
      "CREATE INDEX `stores_user_idx` ON `stores` (`user_id`);",
      "ALTER TABLE `users` ADD `active_store_id` text;",
      "INSERT INTO `stores` (`id`, `user_id`, `name`, `slug`, `created_at`, `updated_at`)\nSELECT `id`, `id`, `store_name`, `store_slug`, `created_at`, `created_at`\nFROM `users`;",
      "UPDATE `users` SET `active_store_id` = `id`;",
      "ALTER TABLE `products` ADD `store_id` text REFERENCES `stores`(`id`) ON DELETE cascade;",
      "UPDATE `products` SET `store_id` = `user_id`;",
      "ALTER TABLE `orders` ADD `store_id` text REFERENCES `stores`(`id`) ON DELETE cascade;",
      "UPDATE `orders` SET `store_id` = `user_id`;"
    ]
  },
  {
    "name": "0009_store_integrations_email.sql",
    "statements": [
      "ALTER TABLE `stores` ADD `email_from` text;",
      "ALTER TABLE `stores` ADD `email_reply_to` text;",
      "ALTER TABLE `stores` ADD `payment_credential_source_store_id` text;",
      "ALTER TABLE `stores` ADD `github_credential_source_store_id` text;",
      "UPDATE `stores`\nSET\n  `payment_credential_source_store_id` = `id`,\n  `github_credential_source_store_id` = `id`;"
    ]
  },
  {
    "name": "0010_customer_portal.sql",
    "statements": [
      "CREATE TABLE `customer_accounts` (\n  `id` text PRIMARY KEY NOT NULL,\n  `email` text NOT NULL,\n  `password_hash` text,\n  `created_at` text NOT NULL,\n  `updated_at` text NOT NULL\n);",
      "CREATE UNIQUE INDEX `customer_accounts_email_unique` ON `customer_accounts` (`email`);",
      "CREATE TABLE `customer_access_tokens` (\n  `id` text PRIMARY KEY NOT NULL,\n  `customer_id` text NOT NULL,\n  `token_hash` text NOT NULL,\n  `expires_at` text NOT NULL,\n  `used_at` text,\n  `created_at` text NOT NULL,\n  FOREIGN KEY (`customer_id`) REFERENCES `customer_accounts`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `customer_access_tokens_token_hash_unique` ON `customer_access_tokens` (`token_hash`);",
      "CREATE INDEX `customer_access_tokens_customer_idx` ON `customer_access_tokens` (`customer_id`);",
      "CREATE INDEX `customer_access_tokens_expiry_idx` ON `customer_access_tokens` (`expires_at`);",
      "ALTER TABLE `orders` ADD `delivery_content` text;",
      "ALTER TABLE `orders` ADD `github_repo_owner` text;",
      "ALTER TABLE `orders` ADD `github_repo_name` text;"
    ]
  },
  {
    "name": "0011_product_fees.sql",
    "statements": [
      "ALTER TABLE `products` ADD `fee_type` text DEFAULT 'fixed' NOT NULL;",
      "ALTER TABLE `products` ADD `fee_value` integer DEFAULT 0 NOT NULL;",
      "ALTER TABLE `orders` ADD `fee_amount` integer DEFAULT 0 NOT NULL;"
    ]
  },
  {
    "name": "0012_transaction_fee_names.sql",
    "statements": [
      "ALTER TABLE `products` RENAME COLUMN `fee_type` TO `transaction_fee_type`;",
      "ALTER TABLE `products` RENAME COLUMN `fee_value` TO `transaction_fee_value`;",
      "ALTER TABLE `orders` RENAME COLUMN `fee_amount` TO `transaction_fee_amount`;"
    ]
  },
  {
    "name": "0013_order_product_snapshots.sql",
    "statements": [
      "ALTER TABLE `orders` ADD `product_description` text;",
      "ALTER TABLE `orders` ADD `product_price` integer;",
      "UPDATE `orders`\nSET\n  `product_description` = (\n    SELECT `description`\n    FROM `products`\n    WHERE `products`.`id` = `orders`.`product_id`\n  ),\n  `product_price` = (\n    SELECT `price`\n    FROM `products`\n    WHERE `products`.`id` = `orders`.`product_id`\n  );"
    ]
  },
  {
    "name": "0014_stripe_payments.sql",
    "statements": [
      "CREATE TABLE `stripe_connections` (\n  `user_id` text NOT NULL,\n  `secret_key_encrypted` text NOT NULL,\n  `webhook_secret_encrypted` text,\n  `account_id` text NOT NULL,\n  `mode` text DEFAULT 'sandbox' NOT NULL,\n  `connected_at` text NOT NULL,\n  PRIMARY KEY(`user_id`, `mode`),\n  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "ALTER TABLE `orders` ADD `stripe_checkout_session_id` text;",
      "ALTER TABLE `orders` ADD `stripe_payment_intent_id` text;"
    ]
  },
  {
    "name": "0015_store_payment_gateway.sql",
    "statements": [
      "ALTER TABLE `stores` ADD `payment_gateway` text DEFAULT 'paypal' NOT NULL;"
    ]
  },
  {
    "name": "0016_product_files.sql",
    "statements": [
      "ALTER TABLE `products` ADD `product_files` text DEFAULT '[]' NOT NULL;",
      "ALTER TABLE `orders` ADD `product_files` text DEFAULT '[]' NOT NULL;"
    ]
  },
  {
    "name": "0017_growth_settings.sql",
    "statements": [
      "ALTER TABLE `stores` ADD `affiliates_enabled` integer DEFAULT 1 NOT NULL;",
      "ALTER TABLE `stores` ADD `affiliate_commission_type` text DEFAULT 'percentage' NOT NULL;",
      "ALTER TABLE `stores` ADD `affiliate_commission_value` real DEFAULT 10 NOT NULL;",
      "ALTER TABLE `stores` ADD `affiliate_commission_duration` text DEFAULT 'one_time' NOT NULL;",
      "ALTER TABLE `stores` ADD `affiliate_attribution_model` text DEFAULT 'last_click' NOT NULL;",
      "ALTER TABLE `stores` ADD `email_campaigns_enabled` integer DEFAULT 1 NOT NULL;"
    ]
  },
  {
    "name": "0018_store_currency_fees.sql",
    "statements": [
      "ALTER TABLE `stores` ADD `currency` text DEFAULT 'USD' NOT NULL;",
      "ALTER TABLE `stores` ADD `transaction_fee_type` text DEFAULT 'fixed' NOT NULL;",
      "ALTER TABLE `stores` ADD `transaction_fee_value` integer DEFAULT 0 NOT NULL;"
    ]
  },
  {
    "name": "0019_store_description.sql",
    "statements": [
      "ALTER TABLE `stores` ADD `description` text DEFAULT '' NOT NULL;"
    ]
  },
  {
    "name": "0020_store_logo.sql",
    "statements": [
      "ALTER TABLE `stores` ADD `logo_image_url` text;"
    ]
  },
  {
    "name": "0021_customer_profile.sql",
    "statements": [
      "ALTER TABLE `customer_accounts` ADD `name` text;",
      "ALTER TABLE `customer_accounts` ADD `avatar_image_url` text;"
    ]
  },
  {
    "name": "0022_product_subscriptions.sql",
    "statements": [
      "ALTER TABLE `products` ADD `billing_type` text DEFAULT 'one_time' NOT NULL;\nALTER TABLE `products` ADD `interval_unit` text;\nALTER TABLE `products` ADD `interval_count` integer DEFAULT 1 NOT NULL;\nALTER TABLE `products` ADD `trial_days` integer DEFAULT 0 NOT NULL;"
    ]
  },
  {
    "name": "0023_environment_data.sql",
    "statements": [
      "ALTER TABLE `products` ADD `environment` text DEFAULT 'sandbox' NOT NULL;",
      "ALTER TABLE `feature_records` ADD `environment` text DEFAULT 'sandbox' NOT NULL;",
      "ALTER TABLE `notifications` ADD `environment` text DEFAULT 'sandbox' NOT NULL;",
      "UPDATE `products` SET `environment` = COALESCE((SELECT `environment` FROM `users` WHERE `users`.`id` = `products`.`user_id`), 'sandbox');",
      "UPDATE `feature_records` SET `environment` = COALESCE((SELECT `environment` FROM `users` WHERE `users`.`id` = `feature_records`.`user_id`), 'sandbox');",
      "UPDATE `notifications` SET `environment` = COALESCE((SELECT `environment` FROM `users` WHERE `users`.`id` = `notifications`.`user_id`), 'sandbox');",
      "DROP INDEX `notifications_user_source_idx`;",
      "CREATE UNIQUE INDEX `notifications_user_environment_source_idx` ON `notifications` (`user_id`,`environment`,`source_key`);"
    ]
  },
  {
    "name": "0024_perpetual_licenses.sql",
    "statements": [
      "ALTER TABLE `products` ADD `license_type` text DEFAULT 'standard' NOT NULL;",
      "ALTER TABLE `products` ADD `license_update_period_unit` text;",
      "ALTER TABLE `products` ADD `license_update_period_count` integer DEFAULT 1 NOT NULL;"
    ]
  }
];
